language: cpp
matrix:
  include:
    - os: linux
    - os: osx
before_install:
  - echo "Installing stack..."
  - |
    if [ `uname` = "Linux" ]; then
      mkdir -p $HOME/bin
      export PATH=$HOME/.local/bin:$PATH
      mkdir -p ~/.local/bin
      curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      git clone http://www.github.com/zeromq/zeromq4-x.git
      cd zeromq4-x
      make -j4 && make check && make install
      cd ..
    elif [ `uname` = "Darwin" ]; then
      brew update
      brew install -v zeromq haskell-stack
    fi
script:
  - export PATH=$PWD:$PATH
  - stack notebook
