sudo: false
cache:
  directories:
  - $HOME/.stack
  - $HOME/zeromq4-x

language: cpp

# TODO: osx takes too long to build initial cache
os:
  - linux
env:
  - RESOLVER="--resolver=lts-9.9"
  - RESOLVER="--resolver=lts-9.10"
  - RESOLVER="--resolver=lts-nightly-2017-10-11"
  - RESOLVER=""

before_install:
  - echo "Installing stack..."
  - |
    if [ `uname` = "Linux" ]; then
      mkdir -p $HOME/bin
      export PATH=$HOME/.local/bin:$PATH
      mkdir -p ~/.local/bin
      curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    elif [ `uname` = "Darwin" ]; then
      brew update
      brew install -v haskell-stack
    fi
  - echo "Zeromq..."
  - |
    if [ `uname` = "Linux" ]; then
      if [ ! -d "$HOME/zeromq4-x/lib" ]; then
        git clone http://www.github.com/zeromq/zeromq4-x.git
        cd zeromq4-x
        ./autogen.sh && ./configure --prefix=$HOME/zeromq4-x && make -j4 && make install
        cd ..
      fi
      export PKG_CONFIG_PATH=$HOME/zeromq4-x/lib/pkgconfig
      export LD_LIBRARY_PATH=$HOME/zeromq4-x/lib
     elif [ `uname` = "Darwin" ]; then
      brew install -v zeromq
    fi
  - pkg-config --modversion libzmq
  - stack setup $RESOLVER

script:
  - export PATH=$PWD:$PATH
  - export STACK_NB_DIR=$PWD
# test within global project
  - echo "echo Check Installation successful" | stack notebook
  - kernel=$(echo 'echo $STACK_NOTEBOOK_KERNEL' | stack notebook) && echo ${kernel}
  - echo "jupyter nbconvert --ExecutePreprocessor.kernel_name=${kernel} --to notebook --execute --stdout ${STACK_NB_DIR}/test/DisplayTest.ipynb" | stack notebook > test.ipynb
  - diff test.ipynb ${STACK_NB_DIR}/test/DisplayTest.ipynb
# test within a specific project
  - stack new test_proj $RESOLVER
  - cd test_proj
  - echo "echo Check Installation successful" | stack notebook
  - kernel=$(echo 'echo $STACK_NOTEBOOK_KERNEL' | stack notebook) && echo ${kernel}
  - echo "jupyter nbconvert --ExecutePreprocessor.kernel_name=${kernel} --to notebook --execute --stdout ${STACK_NB_DIR}/test/DisplayTest.ipynb" | stack notebook > test.ipynb
  - diff test.ipynb ${STACK_NB_DIR}/test/DisplayTest.ipynb

