language: cpp
matrix:
  include:
    - os: linux
#    - os: osx
before_install:
  - echo "Installing stack..."
  - |
    if [ `uname` = "Linux" ]; then
      mkdir -p $HOME/bin
      export PATH=$HOME/.local/bin:$PATH
      mkdir -p ~/.local/bin
      curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    elif [ `uname` = "Darwin" ]; then
      brew update
      brew install -v haskell-stack
    fi
  - echo "Zeromq..."
  - |
    if [ `uname` = "Linux" ]; then
      if [ ! -d "$HOME/zeromq4-x/lib" ]; then
        git clone http://www.github.com/zeromq/zeromq4-x.git
        cd zeromq4-x
        ./autogen.sh && ./configure --prefix=$HOME/zeromq4-x && make -j4 && make install
        export PKG_CONFIG_PATH=$HOME/zeromq4-x/lib/pkgconfig
        export LD_LIBRARY_PATH=$HOME/zeromq4-x/lib
        cd ..
      fi
    elif [ `uname` = "Darwin" ]; then
      brew install -v zeromq
    fi
  - pkg-config --modversion libzmq

script:
  - export PATH=$PWD:$PATH
  - STACK_NOTEBOOK_INSTALL_ONLY=1 stack notebook
